export const authConstants={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const restaurantConstants={
    GET_RESTAURANTS_REQUEST: 'GET_RESTAURANTS_REQUEST',
    GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
    GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE',
    ADD_RESTAURANTS_REQUEST: 'ADD_RESTAURANTS_REQUEST',
    ADD_RESTAURANTS_SUCCESS: 'ADD_RESTAURANTS_SUCCESS',
    ADD_RESTAURANTS_FAILURE: 'ADD_RESTAURANTS_FAILURE'
}

export const userConstants= {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}


